### ISSUE TITLE
Error Code 4102

### ISSUE THREAD

**Issue by Gil401** [aws-robotics/kinesisvideo-ros1#12]
Hi Guys,

As I am trying to stream to my kinesis video stream, I am unable to do so due to the following error:

[ WARN] [1550482172.399163169]: [KinesisVideoFrameTransportCallback] my_stream1 PutFrame failed. Error code: 4102

Any idea what is the reason?

**Comment by ryanewel** [comment]
Hi,

Do you have any more details on the issue? My first guess would be to check that the IAM user you're using has permission to perform PutMedia on my_stream1.

**Comment by juanrh** [comment]
I'm closing this issue, as I understand it is the same problem as #13, but @Gil401 please feel free to reopen the issue if you still have problems. I'll let you know in #13 when the latest version of this package is available on apt-get

Thanks

**Comment by sapanakhemkar** [comment]
Hi 
I am trying to stream video from Nvidia TX2 board. I am getting same error as mentioned in this issue. Below are details -

- Installed h264 encoder using command "sudo apt-get install ros-kinetic-h264-video-encoder"

- Started cv_camera node which is publishing ros camera images on topic /cv_camera/image_raw

- Successfully  compiled kinesis video streamer.

- Exported  below variables  
`export AWS_ACCESS_KEY_ID=my_access_key
export AWS_SECRET_ACCESS_KEY=my_secret_key
export AWS_DEFAULT_REGION=us-east-1 `

- Edited H264 encoder configuration yml file (/opt/ros/kinetic/share/h264_video_encoder/config/sample_configuration.yaml) to register to topic /cv_camera/image_raw 

- Launched  video streamer using command 
  ` roslaunch kinesis_video_streamer sample_application.launch`

- Monitored logs with 'rostopc echo /rosout' 

- Observed bleow warning on /rosout topic

header: 
  seq: 31
  stamp: 
    secs: 1552296487
    nsecs: 402312685
  frame_id: ''
level: 4
name: "/kinesis_video_streamer"
msg: "[KinesisVideoFrameTransportCallback] TX2Stream PutFrame failed. Error code: 4102"
file: "/tmp/binarydeb/ros-kinetic-aws-ros1-common-1.0.0/src/sdk_utils/logging/aws_ros_logger.cpp"
function: "Utils::Logging::AWSROSLogger::LogWarn"
line: 42
topics: [/rosout]

Please let me know whats going wrong in my setup. I donot even see stream created on aws

**Comment by ngthanhtin** [comment]
hi @sapanakhemkar have you fixed the issue? I've also encounter the same problem as you

**Comment by chorhatarahuduketuri** [comment]
I am experiencing this problem in an AWS run community time trial race. 

```
[s3] Successfully uploaded metrics to                  s3 bucket aws-deepracer-data-us-east-1-1 with s3 key data-e484e974-f9ba-4fae-8dbc-dc0d7b77b7f5/models/c399a855-842f-472c-bb8b-9481fb7848f5/metrics/training/training-20211215111804-lfOvfPcVQyi65y4LZ7waig.json.
Testing> Name=main_level/agent, Worker=0, Episode=20, Total reward=1.6403027683936851e+31, Steps=496, Training iteration=0
## agent: Finished evaluation phase. Success rate = 0.0, Avg Total Reward = 1.6403027683936851e+31
Waiting to flush the Mp4 queue for racecar_0...
Done flushing the Mp4 queue for racecar_0...
[s3] Successfully uploaded simtrace_training to              s3 bucket aws-deepracer-data-us-east-1-1 with s3 key data-e484e974-f9ba-4fae-8dbc-dc0d7b77b7f5/models/c399a855-842f-472c-bb8b-9481fb7848f5/sim-trace/training/training-simtrace/0-iteration.csv.
[s3] Successfully uploaded pip to              s3 bucket aws-deepracer-data-us-east-1-1 with s3 key data-e484e974-f9ba-4fae-8dbc-dc0d7b77b7f5/models/c399a855-842f-472c-bb8b-9481fb7848f5/videos/training/training-20211215111804-lfOvfPcVQyi65y4LZ7waig/camera-pip/0-video.mp4.
[s3] Successfully uploaded degree45 to              s3 bucket aws-deepracer-data-us-east-1-1 with s3 key data-e484e974-f9ba-4fae-8dbc-dc0d7b77b7f5/models/c399a855-842f-472c-bb8b-9481fb7848f5/videos/training/training-20211215111804-lfOvfPcVQyi65y4LZ7waig/camera-45degree/0-video.mp4.
[s3] Successfully uploaded topview to              s3 bucket aws-deepracer-data-us-east-1-1 with s3 key data-e484e974-f9ba-4fae-8dbc-dc0d7b77b7f5/models/c399a855-842f-472c-bb8b-9481fb7848f5/videos/training/training-20211215111804-lfOvfPcVQyi65y4LZ7waig/camera-topview/0-video.mp4.
[33m[ WARN] [1639567602.880610919, 69.944000000]: [KinesisVideoFrameTransportCallback] dr-kvs-372026249783-20211215111803-e59dae08-20a0-43e4-9f74-b0bd568d503c PutFrame failed. Error code: 4102[0m
```
