### ISSUE TITLE
no stream on kinesis

### ISSUE THREAD

**Issue by gbr1** [aws-robotics/kinesisvideo-ros1#18]
Hi, just installed your software and I did setup.
In kinesis I created a new user with following policy as described in raspcam tutorial:
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "kinesisvideo:DescribeStream",
                "kinesisvideo:CreateStream",
                "kinesisvideo:GetDataEndpoint",
                "kinesisvideo:PutMedia"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}`

I want just to  publish on kinesis this topic `/camera/color/image_raw`.
So I changed subscription_topic and topic_type.

I putted stream_name "prova2" and on kinesis, after updating webpage, appears stream "prova2" so I believe that connection works.
Unfortunaterly I got black image with loading animation, after a while "no video fragment" appears.

How I can solve it?

**Comment by juanrh** [comment]
Hi Giovanni, 

Thanks for taking a look to our `kinesis_video_streamer node`. I think your are missing adding `kinesisvideo:TagStream` permissions as described on the [aws credentials section](https://github.com/aws-robotics/kinesisvideo-ros1#aws-credentials). 

If that doesn't solve the issue, please indicate operating system, ROS distribution, and the commands used to launch the nodes. Note that as specified in the [run instructions](https://github.com/aws-robotics/kinesisvideo-ros1#run-the-node) you have to launch 3 launch files

```
roslaunch raspicam_nodecamerav2_410x308_30fps.launch
roslaunch h264_video_encoder sample_application.launch
roslaunch kinesis_video_streamer sample_application.launch
```

Thanks

**Comment by gbr1** [comment]
@juanrh just updated my policy adding `kinesisvideo:TagStream`
![screen shot 2019-03-01 at 20 56 16](https://user-images.githubusercontent.com/9216366/53662924-89ee4200-3c64-11e9-9c8a-52febd8463c1.png)

This is what appear on kinesis:
![screen shot 2019-03-01 at 20 57 14](https://user-images.githubusercontent.com/9216366/53662955-a5f1e380-3c64-11e9-94d2-1bb22a656547.png)

My system is Ubuntu 16.04.5 with ROS Kinetic Kame.
I'm using realsense D435 with realsense2_camera standard installation.
Everything works correctly on my system.

I added AWS Credential and Secret key.
I am not using h264 encoder, only this `roslaunch kinesis_video_streamer sample_application.launch`.
Modified parameter for region (I choose Frankfurt so eu-central-1) in `node_sample_configuration.yaml`.
Also subscription topic and topic type in `stream_sample_configuration.yaml`

When your node starts parameters are loaded correctly.

**Comment by mm318** [comment]
Hi @gbr1, how are you producing the stream on `/camera/color/image_raw`?

**Comment by gbr1** [comment]
@mm318 is a topic image from this node: [http://wiki.ros.org/realsense2_camera](http://wiki.ros.org/realsense2_camera).

I can view it in rviz or image_view

**Comment by mm318** [comment]
As Juan mentioned, you need to run the 3 nodes:
```
roslaunch raspicam_node camerav2_410x308_30fps.launch
roslaunch h264_video_encoder sample_application.launch
roslaunch kinesis_video_streamer sample_application.launch
```
In your case, you're already running `realsense2_camera` in place of `raspicam_node`, but you're still missing the `h264_video_encoder` (as you mentioned that you are currently not using h264 encoder). Please see https://github.com/aws-robotics/kinesisvideo-encoder-ros1.

Please let me know if you continue to run into issues.

**Comment by AAlon** [comment]
Closing this as the issue has had no correspondence for three weeks. @gbr1 Please do not hesitate to reopen if further help is needed. Thanks!

**Comment by mchusma** [comment]
Hello, I am having a similar issue here, except that I am using the h264_video_encoder.

So at a high level I am publishing /camera/color/image_raw  from this node: http://wiki.ros.org/realsense2_camera.

I have modified the h264_video_encoder sample_configuration.yaml file to have subscription_topic: "/camera/color/image_raw"
publication_topic: "/video/encoded"

Then, I have left the kinesis_video_streamer effectively unchanged
subscription_topic: /video/encoded

I am able to view the  /camera/color/image_raw topic in rviz and it looks fine.  But when I go to kinesis video stream it creates the stream testStream, but then shows No fragments found.

While I was able to create the stream one time, one other thing is now I am unable to create another one.  I have renamed the kinesis_video_streamer sample_configuration.yaml file to change stream_name: "testStream2", but I do not see a testStream2 appear in kinesis video streams in my aws console.

Any help is appreciated.

**Comment by mchusma** [comment]
For more updates I am seeing in the logs [rosmaster.master][INFO] 2019-08-15 20:16:12,705: +SUB [/raspicam_node/image/compressed] /h264_video_encoder 

I have removed every instance of raspicam_node and cannot find any reference to it anywhere. So it seems like my issue is in trying to adapt the sample, something is causing it to still reference raspicam. Still researching, seems strange. I will likely try to reinstall and create a new launch/config file for the h264 encoder.

**Comment by xabxx** [comment]
@mchusma any updates?

**Comment by mm318** [comment]
Hi @mchusma, was your `h264_video_encoder` node built from source in a local workspace, or were you running the node installed via `apt`?

**Comment by mchusma** [comment]
Hi, so I found the issue, basically what happened was it was installed both from source and installed via apt, which explains my whole problem.  I hadn't realized I had done that. By using solely the one installed via apt it worked for me.

**Comment by mm318** [comment]
Good to hear that you have solved your problem!

We will close this issue now. Please feel free to re-open if the issue arises again.
